static char *extra0 = "\
video_driver                  \"\"\n\
window_position               \"center\"\n\
fullscreen                    1\n\
video_display                 0\n\
aspect_ratio_correct          1\n\
integer_scaling               0\n\
vga_porch_flash               0\n\
window_width                  800\n\
window_height                 600\n\
fullscreen_width              0\n\
fullscreen_height             0\n\
force_software_renderer       0\n\
max_scaling_buffer_pixels     16000000\n\
startup_delay                 1000\n\
show_endoom                   1\n\
show_diskicon                 1\n\
png_screenshots               0\n\
autoload_path                 \"\"\n\
vanilla_savegame_limit        1\n\
vanilla_demo_limit            1\n\
vanilla_keyboard_mapping      1\n\
player_name                   \"Laughing Mancubus\"\n\
grabmouse                     1\n\
novert                        0\n\
mouse_acceleration            2.000000\n\
mouse_threshold               10\n\
dclick_use                    1\n\
key_pause                     255\n\
key_menu_activate             27\n\
key_menu_up                   173\n\
key_menu_down                 175\n\
key_menu_left                 172\n\
key_menu_right                174\n\
key_menu_back                 127\n\
key_menu_forward              13\n\
key_menu_confirm              121\n\
key_menu_abort                110\n\
key_menu_help                 187\n\
key_menu_save                 188\n\
key_menu_load                 189\n\
key_menu_volume               190\n\
key_menu_detail               191\n\
key_menu_qsave                192\n\
key_menu_endgame              193\n\
key_menu_messages             194\n\
key_menu_qload                195\n\
key_menu_quit                 196\n\
key_menu_gamma                215\n\
key_spy                       216\n\
key_menu_incscreen            61\n\
key_menu_decscreen            45\n\
key_menu_screenshot           0\n\
key_map_toggle                9\n\
key_map_north                 173\n\
key_map_south                 175\n\
key_map_east                  174\n\
key_map_west                  172\n\
key_map_zoomin                61\n\
key_map_zoomout               45\n\
key_map_maxzoom               48\n\
key_map_follow                102\n\
key_map_grid                  103\n\
key_map_mark                  109\n\
key_map_clearmark             99\n\
key_weapon1                   49\n\
key_weapon2                   50\n\
key_weapon3                   51\n\
key_weapon4                   52\n\
key_weapon5                   53\n\
key_weapon6                   54\n\
key_weapon7                   55\n\
key_weapon8                   56\n\
key_prevweapon                0\n\
key_nextweapon                0\n\
key_arti_quartz               0\n\
key_arti_urn                  0\n\
key_arti_bomb                 0\n\
key_arti_tome                 127\n\
key_arti_ring                 0\n\
key_arti_chaosdevice          0\n\
key_arti_shadowsphere         0\n\
key_arti_wings                0\n\
key_arti_torch                0\n\
key_arti_morph                0\n\
key_arti_all                  127\n\
key_arti_health               92\n\
key_arti_poisonbag            48\n\
key_arti_blastradius          57\n\
key_arti_teleport             56\n\
key_arti_teleportother        55\n\
key_arti_egg                  54\n\
key_arti_invulnerability      53\n\
key_message_refresh           13\n\
key_demo_quit                 113\n\
";
